[crates]
hashbrown = { name = 'hashbrown', version = '0.17.1' }
getrandom = { name = 'getrandom', version = '0.4.3' }
syn = { name = 'syn', version = '3.0.3' }
windows-sys = { name = 'windows-sys', version = '0.61.2' }
rand = { name = 'rand', version = '0.10.2' }
rand_core = { name = 'rand_core', version = '0.10.1' }
bitflags = { name = 'bitflags', version = '2.13.1' }
thiserror-impl = { name = 'thiserror-impl', version = '2.0.19' }
thiserror = { name = 'thiserror', version = '2.0.19' }
libc = { name = 'libc', version = '1.0.0-alpha.4' }
indexmap = { name = 'indexmap', version = '2.14.0' }
quote = { name = 'quote', version = '1.0.47' }
itertools = { name = 'itertools', version = '0.15.0' }
proc-macro2 = { name = 'proc-macro2', version = '1.0.107' }
memchr = { name = 'memchr', version = '2.8.3' }
unicode-ident = { name = 'unicode-ident', version = '1.0.24' }
base64 = { name = 'base64', version = '0.23.0' }
rand_chacha = { name = 'rand_chacha', version = '0.10.0' }
cfg-if = { name = 'cfg-if', version = '1.0.4' }
itoa = { name = 'itoa', version = '1.0.18' }
socket2 = { name = 'socket2', version = '0.6.5' }
heck = { name = 'heck', version = '0.5.0' }
serde_json = { name = 'serde_json', version = '1.0.151' }
serde = { name = 'serde', version = '1.0.229' }
regex-syntax = { name = 'regex-syntax', version = '0.8.11' }
serde_derive = { name = 'serde_derive', version = '1.0.229' }
once_cell = { name = 'once_cell', version = '1.21.4' }
cc = { name = 'cc', version = '1.4.0' }
autocfg = { name = 'autocfg', version = '1.5.1' }
windows_x86_64_msvc = { name = 'windows_x86_64_msvc', version = '0.53.1' }
cpufeatures = { name = 'cpufeatures', version = '0.3.0' }
digest = { name = 'digest', version = '0.11.3' }
log = { name = 'log', version = '0.4.33' }
windows-targets = { name = 'windows-targets', version = '0.53.5' }
rustix = { name = 'rustix', version = '1.1.4' }
regex-automata = { name = 'regex-automata', version = '0.4.16' }
smallvec = { name = 'smallvec', version = '2.0.0-alpha.12' }
windows_x86_64_gnu = { name = 'windows_x86_64_gnu', version = '0.53.1' }
block-buffer = { name = 'block-buffer', version = '0.12.1' }
windows_aarch64_msvc = { name = 'windows_aarch64_msvc', version = '0.53.1' }
windows_i686_msvc = { name = 'windows_i686_msvc', version = '0.53.1' }
windows_i686_gnu = { name = 'windows_i686_gnu', version = '0.53.1' }
linux-raw-sys = { name = 'linux-raw-sys', version = '0.12.1' }
windows_x86_64_gnullvm = { name = 'windows_x86_64_gnullvm', version = '0.53.1' }
windows_aarch64_gnullvm = { name = 'windows_aarch64_gnullvm', version = '0.53.1' }
crypto-common = { name = 'crypto-common', version = '0.2.2' }
winnow = { name = 'winnow', version = '1.0.4' }
zerocopy = { name = 'zerocopy', version = '0.9.0-alpha.0' }
mio = { name = 'mio', version = '1.2.2' }
regex = { name = 'regex', version = '1.13.1' }
pin-project-lite = { name = 'pin-project-lite', version = '0.2.17' }
sha2 = { name = 'sha2', version = '0.11.0' }
clap = { name = 'clap', version = '4.6.4' }
bytes = { name = 'bytes', version = '1.12.1' }
http = { name = 'http', version = '1.5.0' }
aho-corasick = { name = 'aho-corasick', version = '1.1.4' }
serde_core = { name = 'serde_core', version = '1.0.229' }
parking_lot_core = { name = 'parking_lot_core', version = '0.9.12' }
shlex = { name = 'shlex', version = '2.0.1' }
tokio = { name = 'tokio', version = '1.53.1' }
ryu = { name = 'ryu', version = '1.0.23' }
version_check = { name = 'version_check', version = '0.9.5' }
strsim = { name = 'strsim', version = '0.11.1' }
parking_lot = { name = 'parking_lot', version = '0.12.5' }
toml_datetime = { name = 'toml_datetime', version = '1.1.1+spec-1.1.0' }
futures-core = { name = 'futures-core', version = '0.3.33' }
typenum = { name = 'typenum', version = '1.20.1' }
slab = { name = 'slab', version = '0.4.12' }
futures-util = { name = 'futures-util', version = '0.3.33' }
either = { name = 'either', version = '1.17.0' }
futures-task = { name = 'futures-task', version = '0.3.33' }
semver = { name = 'semver', version = '1.0.28' }
lock_api = { name = 'lock_api', version = '0.4.14' }
foldhash = { name = 'foldhash', version = '0.2.0' }
equivalent = { name = 'equivalent', version = '1.0.2' }
clap_lex = { name = 'clap_lex', version = '1.1.0' }
anyhow = { name = 'anyhow', version = '1.0.104' }
rustc-hash = { name = 'rustc-hash', version = '2.1.3' }
toml = { name = 'toml', version = '1.1.4+spec-1.1.0' }
num-traits = { name = 'num-traits', version = '0.2.19' }
errno = { name = 'errno', version = '0.3.14' }
scopeguard = { name = 'scopeguard', version = '1.2.0' }
rustls = { name = 'rustls', version = '0.24.0-dev.1' }
fastrand = { name = 'fastrand', version = '2.5.0' }
futures-sink = { name = 'futures-sink', version = '0.3.33' }
generic-array = { name = 'generic-array', version = '1.4.4' }
futures-channel = { name = 'futures-channel', version = '0.3.33' }
hyper = { name = 'hyper', version = '1.11.0' }
zmij = { name = 'zmij', version = '1.0.23' }
anstyle = { name = 'anstyle', version = '1.0.14' }
percent-encoding = { name = 'percent-encoding', version = '2.3.2' }
http-body = { name = 'http-body', version = '1.1.0' }
idna = { name = 'idna', version = '1.1.0' }
clap_builder = { name = 'clap_builder', version = '4.6.2' }
futures-io = { name = 'futures-io', version = '0.3.33' }
tracing-core = { name = 'tracing-core', version = '0.1.36' }
rustls-webpki = { name = 'rustls-webpki', version = '0.104.0-alpha.7' }
tokio-macros = { name = 'tokio-macros', version = '2.7.2' }
crossbeam-utils = { name = 'crossbeam-utils', version = '0.8.22' }
tracing = { name = 'tracing', version = '0.1.44' }
toml_edit = { name = 'toml_edit', version = '0.25.13+spec-1.1.0' }
url = { name = 'url', version = '2.5.8' }
rustversion = { name = 'rustversion', version = '1.0.23' }
lazy_static = { name = 'lazy_static', version = '1.5.0' }
yoke = { name = 'yoke', version = '0.8.3' }
clap_derive = { name = 'clap_derive', version = '4.6.4' }
futures-macro = { name = 'futures-macro', version = '0.3.33' }
ppv-lite86 = { name = 'ppv-lite86', version = '0.2.21' }
find-msvc-tools = { name = 'find-msvc-tools', version = '0.1.9' }
synstructure = { name = 'synstructure', version = '0.13.2' }
tinystr = { name = 'tinystr', version = '0.8.3' }
form_urlencoded = { name = 'form_urlencoded', version = '1.2.2' }
webpki-roots = { name = 'webpki-roots', version = '1.0.9' }
yoke-derive = { name = 'yoke-derive', version = '0.8.2' }
zerofrom = { name = 'zerofrom', version = '0.1.8' }
icu_properties_data = { name = 'icu_properties_data', version = '2.2.0' }
icu_properties = { name = 'icu_properties', version = '2.2.0' }
litemap = { name = 'litemap', version = '0.8.2' }
icu_provider = { name = 'icu_provider', version = '2.2.0' }
icu_collections = { name = 'icu_collections', version = '2.2.0' }
tempfile = { name = 'tempfile', version = '3.27.0' }
zerovec = { name = 'zerovec', version = '0.11.6' }
untrusted = { name = 'untrusted', version = '0.9.0' }
anstream = { name = 'anstream', version = '1.0.0' }
uuid = { name = 'uuid', version = '1.24.0' }
zerovec-derive = { name = 'zerovec-derive', version = '0.11.3' }
icu_normalizer_data = { name = 'icu_normalizer_data', version = '2.2.0' }
writeable = { name = 'writeable', version = '0.6.3' }
anstyle-parse = { name = 'anstyle-parse', version = '1.0.0' }
icu_normalizer = { name = 'icu_normalizer', version = '2.2.0' }
stable_deref_trait = { name = 'stable_deref_trait', version = '1.2.1' }
miniz_oxide = { name = 'miniz_oxide', version = '0.9.1' }
signal-hook-registry = { name = 'signal-hook-registry', version = '1.4.8' }
nix = { name = 'nix', version = '0.31.3' }
zerofrom-derive = { name = 'zerofrom-derive', version = '0.1.7' }
colorchoice = { name = 'colorchoice', version = '1.0.5' }
futures-executor = { name = 'futures-executor', version = '0.3.33' }
h2 = { name = 'h2', version = '0.4.15' }
reqwest = { name = 'reqwest', version = '0.13.4' }
futures = { name = 'futures', version = '0.3.33' }
time = { name = 'time', version = '0.3.54' }
idna_adapter = { name = 'idna_adapter', version = '1.2.2' }
redox_syscall = { name = 'redox_syscall', version = '0.9.1' }
displaydoc = { name = 'displaydoc', version = '0.2.7' }
tokio-rustls = { name = 'tokio-rustls', version = '0.26.4' }
zeroize = { name = 'zeroize', version = '1.9.0' }
zerocopy-derive = { name = 'zerocopy-derive', version = '0.9.0-alpha.0' }
tower = { name = 'tower', version = '0.5.3' }
darling_macro = { name = 'darling_macro', version = '0.23.0' }
darling_core = { name = 'darling_core', version = '0.23.0' }
darling = { name = 'darling', version = '0.23.0' }
tracing-attributes = { name = 'tracing-attributes', version = '0.1.31' }
windows_i686_gnullvm = { name = 'windows_i686_gnullvm', version = '0.53.1' }
fnv = { name = 'fnv', version = '1.0.7' }
anstyle-query = { name = 'anstyle-query', version = '1.1.5' }
chrono = { name = 'chrono', version = '0.4.45' }
unicode-width = { name = 'unicode-width', version = '0.2.2' }
ring = { name = 'ring', version = '0.17.14' }
wasi = { name = 'wasi', version = '0.14.7+wasi-0.2.4' }
tokio-util = { name = 'tokio-util', version = '0.7.19' }
subtle = { name = 'subtle', version = '2.6.1' }
time-core = { name = 'time-core', version = '0.1.9' }
httparse = { name = 'httparse', version = '1.10.1' }
rustc_version = { name = 'rustc_version', version = '0.4.1' }
num-conv = { name = 'num-conv', version = '0.2.2' }
pkg-config = { name = 'pkg-config', version = '0.3.33' }
utf8parse = { name = 'utf8parse', version = '0.2.2' }
byteorder = { name = 'byteorder', version = '1.5.0' }
tinyvec = { name = 'tinyvec', version = '1.12.0' }
is_terminal_polyfill = { name = 'is_terminal_polyfill', version = '1.70.2' }
utf8_iter = { name = 'utf8_iter', version = '1.0.4' }
sync_wrapper = { name = 'sync_wrapper', version = '1.0.2' }
deranged = { name = 'deranged', version = '0.5.8' }
windows-link = { name = 'windows-link', version = '0.2.1' }
time-macros = { name = 'time-macros', version = '0.2.32' }
ahash = { name = 'ahash', version = '0.8.12' }
serde_spanned = { name = 'serde_spanned', version = '1.1.1' }
adler2 = { name = 'adler2', version = '2.0.1' }
thread_local = { name = 'thread_local', version = '1.1.10' }
hyper-rustls = { name = 'hyper-rustls', version = '0.27.9' }
nom = { name = 'nom', version = '8.0.0' }
crc32fast = { name = 'crc32fast', version = '1.5.0' }
zerotrie = { name = 'zerotrie', version = '0.2.4' }
icu_locale_core = { name = 'icu_locale_core', version = '2.2.0' }
potential_utf = { name = 'potential_utf', version = '0.1.5' }
iana-time-zone = { name = 'iana-time-zone', version = '0.1.65' }
tracing-subscriber = { name = 'tracing-subscriber', version = '0.3.23' }
flate2 = { name = 'flate2', version = '1.1.9' }
schemars = { name = 'schemars', version = '1.2.2' }
cfg_aliases = { name = 'cfg_aliases', version = '0.2.2' }
openssl-probe = { name = 'openssl-probe', version = '0.2.1' }
rustls-pki-types = { name = 'rustls-pki-types', version = '1.15.1' }
walkdir = { name = 'walkdir', version = '2.5.0' }
crossbeam-epoch = { name = 'crossbeam-epoch', version = '0.9.20' }
powerfmt = { name = 'powerfmt', version = '0.2.0' }
tinyvec_macros = { name = 'tinyvec_macros', version = '0.1.1' }
r-efi = { name = 'r-efi', version = '7.0.0' }
bumpalo = { name = 'bumpalo', version = '3.20.3' }
phf_shared = { name = 'phf_shared', version = '0.14.0' }
tower-service = { name = 'tower-service', version = '0.3.3' }
