// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

pub static LINTS: &[&::declare_clippy_lint::LintInfo] = &[
    crate::char_indices_as_byte_indices::CHAR_INDICES_AS_BYTE_INDICES_INFO,
    crate::empty_loop::EMPTY_LOOP_INFO,
    crate::explicit_counter_loop::EXPLICIT_COUNTER_LOOP_INFO,
    crate::explicit_into_iter_loop::EXPLICIT_INTO_ITER_LOOP_INFO,
    crate::explicit_iter_loop::EXPLICIT_ITER_LOOP_INFO,
    crate::for_kv_map::FOR_KV_MAP_INFO,
    crate::infinite_loop::INFINITE_LOOP_INFO,
    crate::iter_next_loop::ITER_NEXT_LOOP_INFO,
    crate::manual_find::MANUAL_FIND_INFO,
    crate::manual_flatten::MANUAL_FLATTEN_INFO,
    crate::manual_memcpy::MANUAL_MEMCPY_INFO,
    crate::manual_slice_fill::MANUAL_SLICE_FILL_INFO,
    crate::manual_while_let_some::MANUAL_WHILE_LET_SOME_INFO,
    crate::missing_spin_loop::MISSING_SPIN_LOOP_INFO,
    crate::mut_range_bound::MUT_RANGE_BOUND_INFO,
    crate::needless_range_loop::NEEDLESS_RANGE_LOOP_INFO,
    crate::never_loop::NEVER_LOOP_INFO,
    crate::same_item_push::SAME_ITEM_PUSH_INFO,
    crate::single_element_loop::SINGLE_ELEMENT_LOOP_INFO,
    crate::unused_enumerate_index::UNUSED_ENUMERATE_INDEX_INFO,
    crate::while_float::WHILE_FLOAT_INFO,
    crate::while_immutable_condition::WHILE_IMMUTABLE_CONDITION_INFO,
    crate::while_let_loop::WHILE_LET_LOOP_INFO,
    crate::while_let_on_iterator::WHILE_LET_ON_ITERATOR_INFO,
];
