// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

pub static LINTS: &[&::declare_clippy_lint::LintInfo] = &[
    crate::CHAR_INDICES_AS_BYTE_INDICES_INFO,
    crate::EMPTY_LOOP_INFO,
    crate::EXPLICIT_COUNTER_LOOP_INFO,
    crate::EXPLICIT_INTO_ITER_LOOP_INFO,
    crate::EXPLICIT_ITER_LOOP_INFO,
    crate::FOR_KV_MAP_INFO,
    crate::INFINITE_LOOP_INFO,
    crate::ITER_NEXT_LOOP_INFO,
    crate::MANUAL_FIND_INFO,
    crate::MANUAL_FLATTEN_INFO,
    crate::MANUAL_MEMCPY_INFO,
    crate::MANUAL_SLICE_FILL_INFO,
    crate::MANUAL_WHILE_LET_SOME_INFO,
    crate::MISSING_SPIN_LOOP_INFO,
    crate::MUT_RANGE_BOUND_INFO,
    crate::NEEDLESS_RANGE_LOOP_INFO,
    crate::NEVER_LOOP_INFO,
    crate::SAME_ITEM_PUSH_INFO,
    crate::SINGLE_ELEMENT_LOOP_INFO,
    crate::UNUSED_ENUMERATE_INDEX_INFO,
    crate::WHILE_FLOAT_INFO,
    crate::WHILE_IMMUTABLE_CONDITION_INFO,
    crate::WHILE_LET_LOOP_INFO,
    crate::WHILE_LET_ON_ITERATOR_INFO,
];
