//@no-rustfix: the suggestion requires the user to verify the intended iteration order

#![warn(clippy::double_rev_map)]

struct FakeIter(std::ops::Range<i32>);

impl FakeIter {
    fn rev(self) -> Self {
        self
    }
}

impl DoubleEndedIterator for FakeIter {
    fn next_back(&mut self) -> Option<Self::Item> {
        self.0.next_back()
    }
}

impl Iterator for FakeIter {
    type Item = i32;

    fn next(&mut self) -> Option<Self::Item> {
        self.0.next()
    }
}

struct FakeMethods;

impl FakeMethods {
    fn rev(self) -> Self {
        self
    }

    fn map<F>(self, _: F) -> Self
    where
        F: FnMut(i32) -> i32,
    {
        self
    }
}

fn main() {
    let _: Vec<_> = (0..3).rev().map(|x| x + 1).rev().collect();
    //~^ double_rev_map

    // Only one reverse: intentional reverse-order output.
    let _: Vec<_> = (0..3).rev().map(|x| x + 1).collect();

    // The outer reverse is intentional.
    let _: Vec<_> = (0..3).map(|x| x + 1).rev().collect();

    // `enumerate` is direction-sensitive; the lint must be map-only.
    let _: Vec<_> = (0..3).rev().enumerate().rev().collect();

    // The first `rev` is inherent with same spelling.
    let _: Vec<_> = FakeIter(0..4).rev().map(|x| x + 1).rev().collect();

    // All methods are inherent.
    FakeMethods.rev().map(|x| x + 1).rev();

    macro_rules! outer_rev {
        ($iter:expr) => {
            $iter.rev()
        };
    }

    // Do not lint calls generated by macros.
    let _: Vec<_> = outer_rev!((0..3).rev().map(|x| x + 1)).collect();
}
