#![warn(clippy::method_shadow_field)]

use std::ops::Deref;

// Struct
struct Circle {
    radius: f32,
    pub diameter: f32,
    //
    bar: i32,
    pub var: i32,
    //
    extra: i32,
}

impl Circle {
    // Shadows pub or non-pub field names:
    fn radius(self) {}
    //~^ method_shadow_field
    fn diameter(self) {}
    //~^ method_shadow_public_field

    // Do not shadow anything
    fn other(self) {}
    fn another(self) {}

    // Only methods are linted
    fn extra() {}
}

// Union
union Counter {
    small: i8,
    pub large: i64,
}

impl Counter {
    // shadows pub or non-pub field names:
    fn small(self) {}
    //~^ method_shadow_field
    fn large(self) {}
    //~^ method_shadow_public_field

    // do not shadow anything
    fn tick(self) {}
}

// Enum
enum Numbers {
    One,
    Two,
    Last,
}

impl Numbers {
    // fields differ in naming from methods: One vs one(), so they don't clash

    // do not shadow anything
    fn smallest(self) {}
    fn last(self) {}
}

// Deref
struct Inner {
    foo: String,
    pub pub_foo: String,
}

struct Wrapper {
    inner: Inner,
}

impl Wrapper {
    fn foo(&self) {} // not linted
    fn pub_foo(&self) {} // not linted
}

impl Deref for Wrapper {
    type Target = Inner;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

fn deref_test() {
    let inner = Inner {
        foo: String::from("inner"),
        pub_foo: String::from("inner_pub"),
    };
    let wrapper = Wrapper { inner };

    wrapper.foo();
    wrapper.pub_foo();
}

// Trait
trait DefaultName {
    fn bar(&self) {}
}

impl DefaultName for Circle {
    fn bar(&self) {} // not linted
}

// Generics and lifetimes
struct GenericStruct<'a, T> {
    data: &'a T,
}

impl<'a, T> GenericStruct<'a, T> {
    fn data(&self) {}
    //~^ method_shadow_field
}

// Multiple impl blocks
struct MultiImpl {
    a: i32,
    b: i32,
}

impl MultiImpl {
    fn a(&self) {}
    //~^ method_shadow_field
}

impl MultiImpl {
    fn b(&self) {}
    //~^ method_shadow_field
}

// Macros
struct MacroStruct {
    mac_field: i32,
}

macro_rules! generate_method {
    () => {
        impl MacroStruct {
            // should not lint because it is generated by a macro
            fn mac_field(&self) {}
        }
    };
}

generate_method!();

// pub(crate), pub(super)
mod internal {
    pub struct RestrictedVisibility {
        pub(crate) crate_field: i32,
        pub(super) super_field: i32,
    }

    impl RestrictedVisibility {
        pub fn crate_field(&self) {}
        //~^ method_shadow_field

        pub fn super_field(&self) {}
        //~^ method_shadow_field
    }
}

// type alias
struct Original {
    data: i32,
}

type Aliased = Original;

impl Aliased {
    fn data(&self) {}
    //~^ method_shadow_field
}

fn main() {
    deref_test();
}
