[package]
name = "clippy_lints"
# begin automatic update
version = "0.1.56"
# end automatic update
description = "A bunch of helpful lints to avoid common pitfalls in Rust"
repository = "https://github.com/rust-lang/rust-clippy"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["clippy", "lint", "plugin"]
edition = "2018"

[dependencies]
cargo_metadata = "0.14.0"
clippy_utils = { path = "../clippy_utils" }
if_chain = "1.0.2"
itertools = "0.10.1"
pulldown-cmark = { version = "0.8.0", default-features = false }
quine-mc_cluskey = "0.2.4"
regex-syntax = "0.6.25"
serde = { version = "1.0.129", features = ["derive"] }
serde_json = { version = "1.0.66", optional = true }
toml = "0.5.8"
unicode-normalization = "0.1.19"
unicode-script = { version = "0.5.3", default-features = false }
semver = "1.0.4"
rustc-semver = "1.1.0"
# NOTE: cargo requires serde feat in its url dep
# see <https://github.com/rust-lang/rust/pull/63587#issuecomment-522343864>
url = { version = "2.2.2", features = ["serde"] }

[features]
deny-warnings = ["clippy_utils/deny-warnings"]
# build clippy with internal lints enabled, off by default
internal-lints = ["clippy_utils/internal-lints"]
metadata-collector-lint = ["serde_json", "clippy_utils/metadata-collector-lint"]

[package.metadata.rust-analyzer]
# This crate uses #[feature(rustc_private)]
rustc_private = true
