[package]
name = "clippy_utils"
version = "0.1.63"
edition = "2021"
publish = false

[dependencies]
arrayvec = { version = "0.7", default-features = false }
if_chain = "1.0"
rustc-semver = "1.1"

[features]
deny-warnings = []
internal = []

[package.metadata.rust-analyzer]
# This crate uses #[feature(rustc_private)]
rustc_private = true
