[package]
name = "clippy_mir"
version = "0.0.1"
edition = "2024"

[dependencies]
clippy_data_structures = { path = "../clippy_data_structures" }
indexmap = "2.0.0"

[package.metadata.rust-analyzer]
# This package uses #[feature(rustc_private)]
rustc_private = true
