// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

store.register_group(true, "clippy::perf", Some("clippy_perf"), [
    Some(LintId::of(entry::MAP_ENTRY)),
    Some(LintId::of(escape::BOXED_LOCAL)),
    Some(LintId::of(format_args::FORMAT_IN_FORMAT_ARGS)),
    Some(LintId::of(format_args::TO_STRING_IN_FORMAT_ARGS)),
    Some(LintId::of(large_const_arrays::LARGE_CONST_ARRAYS)),
    Some(LintId::of(large_enum_variant::LARGE_ENUM_VARIANT)),
    Some(LintId::of(loops::MANUAL_MEMCPY)),
    Some(LintId::of(loops::NEEDLESS_COLLECT)),
    Some(LintId::of(methods::EXPECT_FUN_CALL)),
    Some(LintId::of(methods::EXTEND_WITH_DRAIN)),
    Some(LintId::of(methods::ITER_NTH)),
    Some(LintId::of(methods::ITER_OVEREAGER_CLONED)),
    Some(LintId::of(methods::MANUAL_STR_REPEAT)),
    Some(LintId::of(methods::OR_FUN_CALL)),
    Some(LintId::of(methods::SINGLE_CHAR_PATTERN)),
    Some(LintId::of(methods::UNNECESSARY_TO_OWNED)),
    Some(LintId::of(misc::CMP_OWNED)),
    Some(LintId::of(redundant_clone::REDUNDANT_CLONE)),
    Some(LintId::of(slow_vector_initialization::SLOW_VECTOR_INITIALIZATION)),
    Some(LintId::of(stable_sort_primitive::STABLE_SORT_PRIMITIVE)),
    Some(LintId::of(types::BOX_COLLECTION)),
    Some(LintId::of(types::REDUNDANT_ALLOCATION)),
    Some(LintId::of(vec::USELESS_VEC)),
    Some(LintId::of(vec_init_then_push::VEC_INIT_THEN_PUSH)),
].iter().copied().flatten().collect::<Vec<_>>())
