// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

store.register_group(true, "clippy::suspicious", Some("clippy_suspicious"), [
    Some(LintId::of(assign_ops::MISREFACTORED_ASSIGN_OP)),
    Some(LintId::of(attrs::BLANKET_CLIPPY_RESTRICTION_LINTS)),
    Some(LintId::of(eval_order_dependence::EVAL_ORDER_DEPENDENCE)),
    Some(LintId::of(float_equality_without_abs::FLOAT_EQUALITY_WITHOUT_ABS)),
    Some(LintId::of(formatting::SUSPICIOUS_ASSIGNMENT_FORMATTING)),
    Some(LintId::of(formatting::SUSPICIOUS_ELSE_FORMATTING)),
    Some(LintId::of(formatting::SUSPICIOUS_UNARY_OP_FORMATTING)),
    Some(LintId::of(loops::EMPTY_LOOP)),
    Some(LintId::of(loops::FOR_LOOPS_OVER_FALLIBLES)),
    Some(LintId::of(loops::MUT_RANGE_BOUND)),
    Some(LintId::of(methods::SUSPICIOUS_MAP)),
    Some(LintId::of(mut_key::MUTABLE_KEY_TYPE)),
    Some(LintId::of(octal_escapes::OCTAL_ESCAPES)),
    Some(LintId::of(suspicious_trait_impl::SUSPICIOUS_ARITHMETIC_IMPL)),
    Some(LintId::of(suspicious_trait_impl::SUSPICIOUS_OP_ASSIGN_IMPL)),
].iter().copied().flatten().collect::<Vec<_>>())
