// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

store.register_group(true, "clippy::nursery", Some("clippy_nursery"), [
    Some(LintId::of(attrs::EMPTY_LINE_AFTER_OUTER_ATTR)),
    Some(LintId::of(cognitive_complexity::COGNITIVE_COMPLEXITY)),
    Some(LintId::of(copies::BRANCHES_SHARING_CODE)),
    Some(LintId::of(equatable_if_let::EQUATABLE_IF_LET)),
    Some(LintId::of(fallible_impl_from::FALLIBLE_IMPL_FROM)),
    Some(LintId::of(floating_point_arithmetic::IMPRECISE_FLOPS)),
    Some(LintId::of(floating_point_arithmetic::SUBOPTIMAL_FLOPS)),
    Some(LintId::of(future_not_send::FUTURE_NOT_SEND)),
    Some(LintId::of(index_refutable_slice::INDEX_REFUTABLE_SLICE)),
    Some(LintId::of(let_if_seq::USELESS_LET_IF_SEQ)),
    Some(LintId::of(missing_const_for_fn::MISSING_CONST_FOR_FN)),
    Some(LintId::of(mutable_debug_assertion::DEBUG_ASSERT_WITH_MUT_CALL)),
    Some(LintId::of(mutex_atomic::MUTEX_ATOMIC)),
    Some(LintId::of(mutex_atomic::MUTEX_INTEGER)),
    Some(LintId::of(non_send_fields_in_send_ty::NON_SEND_FIELDS_IN_SEND_TY)),
    Some(LintId::of(nonstandard_macro_braces::NONSTANDARD_MACRO_BRACES)),
    Some(LintId::of(option_if_let_else::OPTION_IF_LET_ELSE)),
    Some(LintId::of(path_buf_push_overwrite::PATH_BUF_PUSH_OVERWRITE)),
    Some(LintId::of(redundant_pub_crate::REDUNDANT_PUB_CRATE)),
    Some(LintId::of(regex::TRIVIAL_REGEX)),
    Some(LintId::of(strings::STRING_LIT_AS_BYTES)),
    Some(LintId::of(suspicious_operation_groupings::SUSPICIOUS_OPERATION_GROUPINGS)),
    Some(LintId::of(trailing_empty_array::TRAILING_EMPTY_ARRAY)),
    Some(LintId::of(transmute::USELESS_TRANSMUTE)),
    Some(LintId::of(use_self::USE_SELF)),
].iter().copied().flatten().collect::<Vec<_>>())
