// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

store.register_group(true, "clippy::internal", Some("clippy_internal"), [
    Some(LintId::of(utils::internal_lints::CLIPPY_LINTS_INTERNAL)),
    Some(LintId::of(utils::internal_lints::COLLAPSIBLE_SPAN_LINT_CALLS)),
    Some(LintId::of(utils::internal_lints::COMPILER_LINT_FUNCTIONS)),
    Some(LintId::of(utils::internal_lints::DEFAULT_LINT)),
    Some(LintId::of(utils::internal_lints::IF_CHAIN_STYLE)),
    Some(LintId::of(utils::internal_lints::INTERNING_DEFINED_SYMBOL)),
    Some(LintId::of(utils::internal_lints::INVALID_CLIPPY_VERSION_ATTRIBUTE)),
    Some(LintId::of(utils::internal_lints::INVALID_PATHS)),
    Some(LintId::of(utils::internal_lints::LINT_WITHOUT_LINT_PASS)),
    Some(LintId::of(utils::internal_lints::MATCH_TYPE_ON_DIAGNOSTIC_ITEM)),
    Some(LintId::of(utils::internal_lints::MISSING_CLIPPY_VERSION_ATTRIBUTE)),
    Some(LintId::of(utils::internal_lints::OUTER_EXPN_EXPN_DATA)),
    Some(LintId::of(utils::internal_lints::PRODUCE_ICE)),
    Some(LintId::of(utils::internal_lints::UNNECESSARY_SYMBOL_STR)),
].iter().copied().flatten().collect::<Vec<_>>())
