// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

store.register_group(true, "clippy::internal", Some("clippy_internal"), vec![
    #[cfg(nightly)] LintId::of(utils::internal_lints::CLIPPY_LINTS_INTERNAL),
    #[cfg(nightly)] LintId::of(utils::internal_lints::COLLAPSIBLE_SPAN_LINT_CALLS),
    #[cfg(nightly)] LintId::of(utils::internal_lints::COMPILER_LINT_FUNCTIONS),
    #[cfg(nightly)] LintId::of(utils::internal_lints::DEFAULT_DEPRECATION_REASON),
    #[cfg(nightly)] LintId::of(utils::internal_lints::DEFAULT_LINT),
    #[cfg(nightly)] LintId::of(utils::internal_lints::IF_CHAIN_STYLE),
    #[cfg(nightly)] LintId::of(utils::internal_lints::INTERNING_DEFINED_SYMBOL),
    #[cfg(nightly)] LintId::of(utils::internal_lints::INVALID_CLIPPY_VERSION_ATTRIBUTE),
    #[cfg(nightly)] LintId::of(utils::internal_lints::INVALID_PATHS),
    #[cfg(nightly)] LintId::of(utils::internal_lints::LINT_WITHOUT_LINT_PASS),
    #[cfg(nightly)] LintId::of(utils::internal_lints::MATCH_TYPE_ON_DIAGNOSTIC_ITEM),
    #[cfg(nightly)] LintId::of(utils::internal_lints::MISSING_MSRV_ATTR_IMPL),
    #[cfg(nightly)] LintId::of(utils::internal_lints::OUTER_EXPN_EXPN_DATA),
    #[cfg(nightly)] LintId::of(utils::internal_lints::PRODUCE_ICE),
    #[cfg(nightly)] LintId::of(utils::internal_lints::UNNECESSARY_SYMBOL_STR),
])
