[package]
name = "declare_clippy_lint"
version = "0.1.77"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
itertools = "0.11"
quote = "1.0.21"
syn = "2.0"

[features]
deny-warnings = []
