use crate::ir::{
    ActiveLint, ConfDef, LintData, LintPass, LintPassCtor, LintPassCtorArg, LintPassCtorArgs, LintPasses, ParsedLints,
};
use crate::parse::cursor::Cursor;
use crate::utils::{FileUpdater, UpdateMode, UpdateStatus, VecBuf, path_as_crate_mod, update_text_region_fn};
use core::range::Range;
use itertools::Itertools as _;
use std::collections::HashSet;
use std::fmt::Write as _;
use std::path;

const GENERATED_FILE_COMMENT: &str = "// This file was generated by `cargo dev update_lints`.\n\
     // Use that command to update this file and do not edit by hand.\n\
     // Manual edits will be overwritten.\n\n";

const DOCS_LINK: &str = "https://rust-lang.github.io/rust-clippy/main/index.html";

impl ParsedLints<'_> {
    #[expect(clippy::too_many_lines)]
    pub fn gen_decls(&mut self, update_mode: UpdateMode) {
        let mut updater = FileUpdater::default();
        self.lint_passes
            .sort_by_key(|pass| path_as_crate_mod(pass.decl_sp.file.path.get()));

        let mut lints: Vec<_> = self.lints.iter().map(|(&x, y)| (x, y)).collect();
        lints.sort_by_key(|&(x, _)| x);
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "CHANGELOG.md",
            &mut update_text_region_fn(
                "<!-- begin autogenerated links to lint list -->\n",
                "<!-- end autogenerated links to lint list -->",
                |dst| {
                    for &(lint, _) in &lints {
                        writeln!(dst, "[`{lint}`]: {DOCS_LINK}#{lint}").unwrap();
                    }
                },
            ),
        );

        let mut active = Vec::with_capacity(lints.len());
        let mut deprecated = Vec::with_capacity(lints.len() / 8);
        let mut renamed = Vec::with_capacity(lints.len() / 8);
        for &(name, lint) in &lints {
            match &lint.data {
                LintData::Active(data) => {
                    active.push((data.name_upper, path_as_crate_mod(lint.name_sp.file.path.get())));
                },
                LintData::Deprecated(data) => deprecated.push((name, lint.version, data.reason)),
                LintData::Renamed(data) => renamed.push((name, lint.version, data.new_name)),
            }
        }
        active.sort_by_key(|&(_, path)| path);

        // Round to avoid updating the readme every time a lint is added/deprecated.
        let lint_count = active.len() / 50 * 50;
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "README.md",
            &mut update_text_region_fn("[There are over ", " lints included in this crate!]", |dst| {
                write!(dst, "{lint_count}").unwrap();
            }),
        );
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "book/src/README.md",
            &mut update_text_region_fn("[There are over ", " lints included in this crate!]", |dst| {
                write!(dst, "{lint_count}").unwrap();
            }),
        );

        updater.update_loaded_file_checked(
            "cargo dev update_lints",
            update_mode,
            self.deprecated_file,
            &mut |_, src, dst| {
                let mut cursor = Cursor::new(src);
                assert!(
                    cursor.find_ident("declare_with_version") && cursor.find_ident("declare_with_version"),
                    "error reading deprecated lints"
                );
                dst.push_str(&src[..cursor.pos() as usize]);
                dst.push_str("! { DEPRECATED(DEPRECATED_VERSION) = [\n");
                for &(name, version, reason) in &deprecated {
                    write!(
                        dst,
                        "    #[clippy::version = \"{version}\"]\n    (\"clippy::{name}\", \"{reason}\"),\n",
                    )
                    .unwrap();
                }
                dst.push_str(
                    "]}\n\n\
                        #[rustfmt::skip]\n\
                        declare_with_version! { RENAMED(RENAMED_VERSION) = [\n\
                    ",
                );
                for &(name, version, new_name) in &renamed {
                    write!(
                        dst,
                        "    #[clippy::version = \"{version}\"]\n    (\"clippy::{name}\", \"{new_name}\"),\n",
                    )
                    .unwrap();
                }
                dst.push_str("]}\n");
                UpdateStatus::from_changed(src != dst)
            },
        );
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "tests/ui/deprecated.rs",
            &mut |_, src, dst| {
                dst.push_str(GENERATED_FILE_COMMENT);
                for &(lint, _, _) in &deprecated {
                    writeln!(dst, "#![warn(clippy::{lint})] //~ ERROR: lint `clippy::{lint}`").unwrap();
                }
                dst.push_str("\nfn main() {}\n");
                UpdateStatus::from_changed(src != dst)
            },
        );
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "tests/ui/rename.rs",
            &mut move |_, src, dst| {
                let mut seen_lints = HashSet::new();
                dst.push_str(GENERATED_FILE_COMMENT);
                dst.push_str("#![allow(clippy::duplicated_attributes)]\n");
                for &(_, _, new_name) in &renamed {
                    if seen_lints.insert(new_name) {
                        writeln!(dst, "#![allow({new_name})]").unwrap();
                    }
                }
                for &(lint, _, _) in &renamed {
                    writeln!(dst, "#![warn(clippy::{lint})] //~ ERROR: lint `clippy::{lint}`").unwrap();
                }
                dst.push_str("\nfn main() {}\n");
                UpdateStatus::from_changed(src != dst)
            },
        );
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "src/lints.rs",
            &mut |_, src, dst| {
                dst.push_str(GENERATED_FILE_COMMENT);
                dst.push_str("#[rustfmt::skip]\npub static LINTS: &[&::declare_clippy_lint::LintInfo] = &[\n");
                for &(name, (krate, mod_path)) in &active {
                    dst.extend(["    &::", krate, "::"]);
                    for part in mod_path.split(path::MAIN_SEPARATOR) {
                        dst.extend([part, "::"]);
                    }
                    dst.extend([name, "_INFO,\n"]);
                }
                dst.push_str("];\n");
                UpdateStatus::from_changed(src != dst)
            },
        );
        active.sort_unstable_by_key(|&(name, _)| name);
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "src/combined_passes.rs",
            &mut |_, src, dst| {
                gen_combined_lints_file(dst, &active, &self.lint_passes);
                UpdateStatus::from_changed(src != dst)
            },
        );
    }
}

#[expect(clippy::elidable_lifetime_names, clippy::too_many_lines)]
fn gen_combined_lints_file<'cx>(
    dst: &mut String,
    active_lints: &[(&str, (&str, &str))],
    lint_passes: &LintPasses<'cx>,
) {
    let write_lint_list = |dst: &mut String, lints: &[&str], indent: &str| {
        let [lint, ..] = lints else { return };
        let start = active_lints
            .binary_search_by_key(lint, |&(x, _)| x)
            .unwrap_or_else(|_| panic!("missing lint `{lint}`"));
        let mut active = active_lints[start..].iter();
        for &lint in lints {
            let (_, (krate, mod_path)) = active
                .find(|&&(name, _)| lint == name)
                .unwrap_or_else(|| panic!("missing lint `{lint}`"));
            dst.extend(["\n", indent, "::", krate, "::"]);
            for part in mod_path.split(path::MAIN_SEPARATOR) {
                dst.extend([part, "::"]);
            }
            dst.extend([lint, ","]);
        }
    };

    let (early_passes, late_passes) = lint_passes.split_early_late_passes();
    let mut lints_buf: Vec<&str> = Vec::with_capacity(active_lints.len());

    dst.push_str(GENERATED_FILE_COMMENT);
    dst.push_str(
        "\
#![rustfmt::skip]
#![expect(
    non_snake_case,
    non_upper_case_globals,
    clippy::too_many_lines,
    rustc::lint_pass_impl_without_macro,
)]

use clippy_config::Conf;
use clippy_utils::macros::FormatArgsStorage;
use clippy_lints::utils::attr_collector::AttrStorage;
use rustc_data_structures::unord::UnordSet;
use rustc_lint::{
    EarlyContext, EarlyLintPass, LateContext, LateLintPass, Lint, LintId, LintPass, LintVec, early_lint_methods,
    late_lint_methods,
};
use rustc_middle::ty::TyCtxt;

fn is_lint_pass_required(skippable: &UnordSet<LintId>, lints: &[&'static Lint]) -> bool {
    let skippable = !lints.is_empty() && lints.iter().all(|lint| skippable.contains(&LintId::of(lint)));
    !skippable
}

",
    );
    for &pass in &late_passes {
        dst.extend(["static ", pass.name, "_LINTS: &[&Lint] = &["]);
        lints_buf.clear();
        lints_buf.extend(pass.lints.iter().map(|&l| l.rsplit_once("::").unwrap_or(("", l)).1));
        lints_buf.sort_unstable();
        write_lint_list(dst, &lints_buf, "    ");
        dst.push_str("\n];\n");
    }
    dst.push_str(
        "
pub struct CombinedClippyEarlyPass {",
    );
    for pass in &early_passes {
        dst.push_str("\n    ");
        pass.gen_struct_field(dst);
    }
    dst.push_str(
        "
}
impl CombinedClippyEarlyPass {
    pub fn new(conf: &'static Conf, fmt_args: &FormatArgsStorage, attrs: &AttrStorage) -> Self {
        Self {",
    );
    for pass in &early_passes {
        dst.push_str("\n            ");
        pass.gen_struct_init(dst);
    }
    dst.push_str(
        "
        }
    }
}
impl LintPass for CombinedClippyEarlyPass {
    fn name(&self) -> &'static str {
        \"CombinedClippyEarlyPass\"
    }
    fn get_lints(&self) -> LintVec {
        vec![",
    );
    lints_buf.clear();
    for &pass in &early_passes {
        lints_buf.extend(pass.lints.iter().map(|&l| l.rsplit_once("::").unwrap_or(("", l)).1));
    }
    lints_buf.sort_unstable();
    lints_buf.dedup();
    write_lint_list(dst, &lints_buf, "            ");
    dst.push_str(
        "
        ]
    }
}
macro_rules! expand_early_methods {
    ((), [$(fn $name:ident($($param:ident: $param_ty:ty),*);)*]) => {
        impl EarlyLintPass for CombinedClippyEarlyPass {$(
            fn $name(&mut self, cx: &EarlyContext<'_>, $($param: $param_ty),*) {",
    );
    for pass in &early_passes {
        dst.extend([
            "\n                EarlyLintPass::$name(&mut self.",
            pass.name,
            ", cx, $($param),*);",
        ]);
    }
    dst.push_str(
        "
            }
        )*}
    }
}
early_lint_methods!(expand_early_methods, ());

pub struct CombinedClippyLatePass<'tcx> {",
    );
    for pass in &late_passes {
        dst.push_str("\n    ");
        pass.gen_opt_struct_field(dst);
    }
    dst.push_str(
        "
}
impl<'tcx> CombinedClippyLatePass<'tcx> {
    pub fn new(tcx: TyCtxt<'tcx>, conf: &'static Conf, fmt_args: &FormatArgsStorage, attrs: &AttrStorage) -> Self {
        let skippable_lints = tcx.skippable_lints(());
        Self {",
    );
    for pass in &late_passes {
        dst.push_str("\n            ");
        pass.gen_opt_struct_init(dst);
    }
    dst.push_str(
        "
        }
    }
}
impl LintPass for CombinedClippyLatePass<'_> {
    fn name(&self) -> &'static str {
        \"CombinedClippyLatePass\"
    }
    fn get_lints(&self) -> LintVec {
        vec![",
    );
    lints_buf.clear();
    for &pass in &late_passes {
        lints_buf.extend(pass.lints.iter().map(|&l| l.rsplit_once("::").unwrap_or(("", l)).1));
    }
    lints_buf.sort_unstable();
    lints_buf.dedup();
    write_lint_list(dst, &lints_buf, "            ");
    dst.push_str(
        "
        ]
    }
}
macro_rules! expand_late_methods {
    ((), [$(fn $name:ident($($param:ident: $param_ty:ty),*);)*]) => {
        impl<'tcx> LateLintPass<'tcx> for CombinedClippyLatePass<'tcx> {$(
            fn $name(&mut self, cx: &LateContext<'tcx>, $($param: $param_ty),*) {",
    );
    for pass in &late_passes {
        dst.extend([
            "\n                if let Some(pass) = &mut self.",
            pass.name,
            " { LateLintPass::$name(pass, cx, $($param),*); }",
        ]);
    }
    dst.push_str(
        "
            }
        )*}
    }
}
late_lint_methods!(expand_late_methods, ());",
    );
}

impl ActiveLint<'_, '_> {
    pub fn gen_mac(&self, dst: &mut String) {
        dst.push_str("declare_clippy_lint! {");
        write_comment_lines(self.data.docs, "\n    ", dst);
        dst.extend([
            "\n    #[clippy::version = \"",
            self.version,
            "\"]\n    pub ",
            self.data.name_upper,
            ",",
        ]);
        write_comment_lines(self.data.group_comments, "\n    ", dst);
        dst.extend(["\n    ", self.data.group, ",\n    ", self.data.desc]);
        if !self.data.opts.is_empty() {
            dst.extend([",\n    ", self.data.opts]);
        }
        dst.push_str("\n}");
    }
}

impl LintPassCtorArgs {
    fn gen_args_list(self, dst: &mut String) {
        let mut first = true;
        for &arg in &self {
            if !first {
                dst.push_str(", ");
            }
            first = false;
            dst.push_str(match arg {
                LintPassCtorArg::TyCtxt => "tcx",
                LintPassCtorArg::Conf => "conf",
                LintPassCtorArg::FmtArgs => "fmt_args.clone()",
                LintPassCtorArg::Attrs => "attrs.clone()",
            });
        }
    }
}

impl LintPass<'_> {
    pub fn gen_mac(&self, dst: &mut String) {
        let mut line_start = dst.len();
        dst.extend([self.mac.name(), "!("]);
        let has_docs = write_comment_lines(self.docs, "\n    ", dst);
        let (list_indent, list_multi_end, end) = if has_docs {
            dst.push_str("\n    ");
            line_start = dst.len() - 4;
            ("        ", "\n    ", "]\n);")
        } else {
            ("    ", "\n", "]);")
        };
        dst.push_str(self.name);
        if let Some(lt) = self.lt {
            dst.extend(["<", lt, ">"]);
        }
        dst.push_str(" => [");
        let fmt = write_list(
            self.lints.iter().copied(),
            80usize.saturating_sub(dst.len() - line_start),
            list_indent,
            dst,
        );
        if matches!(fmt, ListFmt::MultiLine) {
            dst.push_str(list_multi_end);
        }
        dst.push_str(end);
    }

    pub fn gen_full_path(&self, dst: &mut String) {
        self.decl_sp.file.write_path_as_rust_path(dst);
        dst.extend(["::", self.name]);
    }

    fn gen_opt_struct_field(&self, dst: &mut String) {
        dst.extend([self.name, ": Option<"]);
        self.gen_full_path(dst);
        dst.push_str(if self.lt.is_some() { "<'tcx>>," } else { ">," });
    }

    fn gen_struct_field(&self, dst: &mut String) {
        dst.extend([self.name, ": "]);
        self.gen_full_path(dst);
        dst.push_str(if self.lt.is_some() { "<'tcx>," } else { "," });
    }

    fn gen_struct_init(&self, dst: &mut String) {
        dst.extend([self.name, ": "]);
        self.gen_full_path(dst);
        match self.ctor {
            LintPassCtor::Unit => dst.push(','),
            LintPassCtor::Default => dst.push_str("::default(),"),
            LintPassCtor::New(args) => {
                dst.push_str("::new(");
                args.gen_args_list(dst);
                dst.push_str("),");
            },
        }
    }

    fn gen_opt_struct_init(&self, dst: &mut String) {
        dst.extend([self.name, ": is_lint_pass_required(skippable_lints, ", self.name]);
        match self.ctor {
            LintPassCtor::Unit => {
                dst.push_str("_LINTS).then_some(");
                self.gen_full_path(dst);
                dst.push_str("),");
            },
            LintPassCtor::Default => {
                dst.push_str("_LINTS).then(");
                self.gen_full_path(dst);
                dst.push_str("::default),");
            },
            LintPassCtor::New(args) => {
                dst.push_str("_LINTS).then(|| ");
                self.gen_full_path(dst);
                dst.push_str("::new(");
                args.gen_args_list(dst);
                dst.push_str(")),");
            },
        }
    }
}

impl ConfDef<'_> {
    pub fn gen_file(&mut self, src: &str, dst: &mut String) {
        dst.push_str(&src[..self.decl_sp.range.start as usize]);
        self.gen_mac(src, dst);
        dst.push_str(&src[self.decl_sp.range.end as usize..]);
    }

    pub fn gen_mac(&mut self, src: &str, dst: &mut String) {
        self.opts.sort_unstable_by_key(|o| o.name);
        dst.push_str("define_Conf! {");
        for opt in &mut self.opts {
            let pre_lints = src[opt.decl_range.start as usize..opt.lints_range.start as usize].trim_end();
            if !pre_lints.is_empty() {
                dst.push_str("\n    ");
                dst.push_str(pre_lints);
            }
            let pre_name_text = if opt.lints.is_empty() {
                "\n    "
            } else {
                opt.lints.sort_unstable();
                dst.push_str("\n    #[lints(");
                let fmt = write_list(opt.lints.iter().copied(), 80 - 14, "        ", dst);
                match fmt {
                    ListFmt::SingleLine => ")]\n    ",
                    ListFmt::MultiLine => "\n    )]\n    ",
                }
            };
            dst.push_str(pre_name_text);
            dst.push_str(src[opt.lints_range.end as usize..opt.decl_range.end as usize].trim());
            dst.push(',');
        }
        dst.push_str("\n}");
    }
}

fn write_comment_lines(s: &str, prefix: &str, dst: &mut String) -> bool {
    let mut has_doc = false;
    for line in s.split('\n') {
        let line = line.trim_start();
        if !line.is_empty() {
            has_doc = true;
            dst.extend([prefix, line]);
        }
    }
    has_doc
}

#[derive(Clone, Copy)]
enum ListFmt {
    SingleLine,
    MultiLine,
}

fn write_list<'a>(
    items: impl Iterator<Item = &'a str> + Clone,
    single_line_limit: usize,
    indent: &str,
    dst: &mut String,
) -> ListFmt {
    let len = items.clone().map(str::len).sum::<usize>();
    if len > single_line_limit {
        for item in items {
            dst.extend(["\n", indent, item, ","]);
        }
        ListFmt::MultiLine
    } else {
        let _ = write!(dst, "{}", items.format(", "));
        ListFmt::SingleLine
    }
}

/// Generates the contents of a lint's source file with all the lint and lint pass
/// declarations sorted.
pub fn gen_sorted_lints_file(
    src: &str,
    dst: &mut String,
    lints: &mut [ActiveLint<'_, '_>],
    passes: &mut [LintPass<'_>],
    ranges: &mut VecBuf<Range<u32>>,
    copy_src: &mut dyn FnMut(&str, &mut String),
) {
    ranges.with(|ranges| {
        ranges.extend(lints.iter().map(|x| x.data.decl_range));
        ranges.extend(passes.iter().map(|x| x.decl_sp.range));
        ranges.sort_unstable_by_key(|x| x.start);

        lints.sort_unstable_by_key(|x| x.name);
        passes.sort_by_key(|x| x.name);

        let mut ranges = ranges.iter();
        let pos = if let Some(range) = ranges.next() {
            copy_src(&src[..range.start as usize], dst);
            for lint in &*lints {
                lint.gen_mac(dst);
                dst.push_str("\n\n");
            }
            for pass in passes {
                pass.lints.sort_unstable();
                pass.gen_mac(dst);
                dst.push_str("\n\n");
            }
            range.end
        } else {
            copy_src(src, dst);
            return;
        };

        let pos = ranges.fold(pos, |start, range| {
            let s = &src[start as usize..range.start as usize];
            // Don't keep whitespace between declarations.
            if !s.trim_start().is_empty() {
                let s = if src[..pos as usize].ends_with("\n\n")
                    && let Some(s) = s.strip_prefix("\n\n")
                {
                    // Empty line before and after. Remove one of them.
                    s
                } else {
                    // Remove the line end immediately proceeding a declaration.
                    s.strip_prefix('\n').unwrap_or(s)
                };
                copy_src(s, dst);
            }
            range.end
        });

        // Since we always generate an empty line at the end, make sure to always skip it.
        let s = &src[pos as usize..];
        let s = s.strip_prefix('\n').map_or(s, |s| s.strip_prefix('\n').unwrap_or(s));
        copy_src(s, dst);
    });
}
