use crate::parse::cursor::Cursor;
use crate::parse::{ActiveLint, ConfDef, LintData, LintPass, ParsedLints};
use crate::utils::{FileUpdater, UpdateMode, UpdateStatus, VecBuf, slice_groups, update_text_region_fn};
use core::range::Range;
use itertools::Itertools;
use std::collections::HashSet;
use std::fmt::Write;
use std::path::{self, Path};

const GENERATED_FILE_COMMENT: &str = "// This file was generated by `cargo dev update_lints`.\n\
     // Use that command to update this file and do not edit by hand.\n\
     // Manual edits will be overwritten.\n\n";

const DOCS_LINK: &str = "https://rust-lang.github.io/rust-clippy/master/index.html";

impl ParsedLints<'_> {
    #[expect(clippy::too_many_lines)]
    pub fn gen_decls(&self, update_mode: UpdateMode) {
        let mut updater = FileUpdater::default();

        let mut lints: Vec<_> = self.lints.iter().map(|(&x, y)| (x, y)).collect();
        lints.sort_by_key(|&(x, _)| x);
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "CHANGELOG.md",
            &mut update_text_region_fn(
                "<!-- begin autogenerated links to lint list -->\n",
                "<!-- end autogenerated links to lint list -->",
                |dst| {
                    for &(lint, _) in &lints {
                        writeln!(dst, "[`{lint}`]: {DOCS_LINK}#{lint}").unwrap();
                    }
                },
            ),
        );

        let mut active = Vec::with_capacity(lints.len());
        let mut deprecated = Vec::with_capacity(lints.len() / 8);
        let mut renamed = Vec::with_capacity(lints.len() / 8);
        for &(name, lint) in &lints {
            match &lint.data {
                LintData::Active(_) => active.push((name, lint.name_sp.file.path_as_krate_mod())),
                LintData::Deprecated(data) => deprecated.push((name, lint.version, data.reason)),
                LintData::Renamed(data) => renamed.push((name, lint.version, data.new_name)),
            }
        }
        active.sort_by_key(|&(_, path)| path);

        // Round to avoid updating the readme every time a lint is added/deprecated.
        let lint_count = active.len() / 50 * 50;
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "README.md",
            &mut update_text_region_fn("[There are over ", " lints included in this crate!]", |dst| {
                write!(dst, "{lint_count}").unwrap();
            }),
        );
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "book/src/README.md",
            &mut update_text_region_fn("[There are over ", " lints included in this crate!]", |dst| {
                write!(dst, "{lint_count}").unwrap();
            }),
        );

        updater.update_loaded_file_checked(
            "cargo dev update_lints",
            update_mode,
            self.deprecated_file,
            &mut |_, src, dst| {
                let mut cursor = Cursor::new(src);
                assert!(
                    cursor.find_ident("declare_with_version") && cursor.find_ident("declare_with_version"),
                    "error reading deprecated lints"
                );
                dst.push_str(&src[..cursor.pos() as usize]);
                dst.push_str("! { DEPRECATED(DEPRECATED_VERSION) = [\n");
                for &(name, version, reason) in &deprecated {
                    write!(
                        dst,
                        "    #[clippy::version = \"{version}\"]\n    (\"clippy::{name}\", \"{reason}\"),\n",
                    )
                    .unwrap();
                }
                dst.push_str(
                    "]}\n\n\
                        #[rustfmt::skip]\n\
                        declare_with_version! { RENAMED(RENAMED_VERSION) = [\n\
                    ",
                );
                for &(name, version, new_name) in &renamed {
                    write!(
                        dst,
                        "    #[clippy::version = \"{version}\"]\n    (\"clippy::{name}\", \"{new_name}\"),\n",
                    )
                    .unwrap();
                }
                dst.push_str("]}\n");
                UpdateStatus::from_changed(src != dst)
            },
        );
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "tests/ui/deprecated.rs",
            &mut |_, src, dst| {
                dst.push_str(GENERATED_FILE_COMMENT);
                for &(lint, _, _) in &deprecated {
                    writeln!(dst, "#![warn(clippy::{lint})] //~ ERROR: lint `clippy::{lint}`").unwrap();
                }
                dst.push_str("\nfn main() {}\n");
                UpdateStatus::from_changed(src != dst)
            },
        );
        updater.update_file_checked(
            "cargo dev update_lints",
            update_mode,
            "tests/ui/rename.rs",
            &mut move |_, src, dst| {
                let mut seen_lints = HashSet::new();
                dst.push_str(GENERATED_FILE_COMMENT);
                dst.push_str("#![allow(clippy::duplicated_attributes)]\n");
                for &(_, _, new_name) in &renamed {
                    if seen_lints.insert(new_name) {
                        writeln!(dst, "#![allow({new_name})]").unwrap();
                    }
                }
                for &(lint, _, _) in &renamed {
                    writeln!(dst, "#![warn(clippy::{lint})] //~ ERROR: lint `clippy::{lint}`").unwrap();
                }
                dst.push_str("\nfn main() {}\n");
                UpdateStatus::from_changed(src != dst)
            },
        );

        for lints in slice_groups(&active, |(_, (head, _)), tail| {
            tail.iter().take_while(|(_, (x, _))| head == x).count()
        }) {
            let (_, (krate, _)) = lints[0];
            updater.update_file_checked(
                "cargo dev update_lints",
                update_mode,
                Path::new(krate).join("src/lib.rs"),
                &mut update_text_region_fn(
                    "// begin lints modules, do not remove this comment, it's used in `update_lints`\n",
                    "// end lints modules, do not remove this comment, it's used in `update_lints`",
                    |dst| {
                        let mut prev = "";
                        for &(_, (_, mod_path)) in lints {
                            let module = mod_path.split_once(path::MAIN_SEPARATOR).map_or(mod_path, |(x, _)| x);
                            if module != prev {
                                writeln!(dst, "mod {module};").unwrap();
                                prev = module;
                            }
                        }
                    },
                ),
            );
            updater.update_file_checked(
                "cargo dev update_lints",
                update_mode,
                Path::new(krate).join("src/declared_lints.rs"),
                &mut |_, src, dst| {
                    dst.push_str(GENERATED_FILE_COMMENT);
                    dst.push_str("pub static LINTS: &[&::declare_clippy_lint::LintInfo] = &[\n");
                    let mut buf = String::new();
                    for &(name, (_, mod_path)) in lints {
                        dst.push_str("    crate::");
                        for part in mod_path.split(path::MAIN_SEPARATOR) {
                            dst.push_str(part);
                            dst.push_str("::");
                        }
                        buf.clear();
                        buf.push_str(name);
                        buf.make_ascii_uppercase();
                        let _ = writeln!(dst, "{buf}_INFO,");
                    }
                    dst.push_str("];\n");
                    UpdateStatus::from_changed(src != dst)
                },
            );
        }
    }
}

impl ActiveLint<'_, '_> {
    pub fn gen_mac(&self, dst: &mut String) {
        dst.push_str("declare_clippy_lint! {");
        write_comment_lines(self.data.docs, "\n    ", dst);
        dst.extend(["\n    #[clippy::version = \"", self.version, "\"]\n    pub "]);

        // Lint names are stored in lower case, but the declaration needs to be upper case.
        let name_pos = dst.len();
        dst.push_str(self.name);
        dst[name_pos..].make_ascii_uppercase();
        dst.push(',');

        write_comment_lines(self.data.group_comments, "\n    ", dst);
        dst.extend(["\n    ", self.data.group, ",\n    ", self.data.desc]);
        if !self.data.opts.is_empty() {
            dst.extend([",\n    ", self.data.opts]);
        }
        dst.push_str("\n}");
    }
}

impl LintPass<'_> {
    pub fn gen_mac(&self, dst: &mut String) {
        let mut line_start = dst.len();
        dst.extend([self.mac.name(), "!("]);
        let has_docs = write_comment_lines(self.docs, "\n    ", dst);
        let (list_indent, list_multi_end, end) = if has_docs {
            dst.push_str("\n    ");
            line_start = dst.len() - 4;
            ("        ", "\n    ", "]\n);")
        } else {
            ("    ", "\n", "]);")
        };
        dst.push_str(self.name);
        if let Some(lt) = self.lt {
            dst.extend(["<", lt, ">"]);
        }
        dst.push_str(" => [");
        let fmt = write_list(
            self.lints.iter().copied(),
            80usize.saturating_sub(dst.len() - line_start),
            list_indent,
            dst,
        );
        if matches!(fmt, ListFmt::MultiLine) {
            dst.push_str(list_multi_end);
        }
        dst.push_str(end);
    }
}

impl ConfDef<'_> {
    pub fn gen_file(&mut self, src: &str, dst: &mut String) {
        dst.push_str(&src[..self.decl_sp.range.start as usize]);
        self.gen_mac(src, dst);
        dst.push_str(&src[self.decl_sp.range.end as usize..]);
    }

    pub fn gen_mac(&mut self, src: &str, dst: &mut String) {
        self.opts.sort_unstable_by_key(|o| o.name);
        dst.push_str("define_Conf! {");
        for opt in &mut self.opts {
            let pre_lints = src[opt.decl_range.start as usize..opt.lints_range.start as usize].trim_end();
            if !pre_lints.is_empty() {
                dst.push_str("\n    ");
                dst.push_str(pre_lints);
            }
            let pre_name_text = if opt.lints.is_empty() {
                "\n    "
            } else {
                opt.lints.sort_unstable();
                dst.push_str("\n    #[lints(");
                let fmt = write_list(opt.lints.iter().copied(), 80 - 14, "        ", dst);
                match fmt {
                    ListFmt::SingleLine => ")]\n    ",
                    ListFmt::MultiLine => "\n    )]\n    ",
                }
            };
            dst.push_str(pre_name_text);
            dst.push_str(src[opt.lints_range.end as usize..opt.decl_range.end as usize].trim());
            dst.push(',');
        }
        dst.push_str("\n}");
    }
}

fn write_comment_lines(s: &str, prefix: &str, dst: &mut String) -> bool {
    let mut has_doc = false;
    for line in s.split('\n') {
        let line = line.trim_start();
        if !line.is_empty() {
            has_doc = true;
            dst.extend([prefix, line]);
        }
    }
    has_doc
}

#[derive(Clone, Copy)]
enum ListFmt {
    SingleLine,
    MultiLine,
}

fn write_list<'a>(
    items: impl Iterator<Item = &'a str> + Clone,
    single_line_limit: usize,
    indent: &str,
    dst: &mut String,
) -> ListFmt {
    let len = items.clone().map(str::len).sum::<usize>();
    if len > single_line_limit {
        for item in items {
            dst.extend(["\n", indent, item, ","]);
        }
        ListFmt::MultiLine
    } else {
        let _ = write!(dst, "{}", items.format(", "));
        ListFmt::SingleLine
    }
}

/// Generates the contents of a lint's source file with all the lint and lint pass
/// declarations sorted.
pub fn gen_sorted_lints_file(
    src: &str,
    dst: &mut String,
    lints: &mut [ActiveLint<'_, '_>],
    passes: &mut [LintPass<'_>],
    ranges: &mut VecBuf<Range<u32>>,
    copy_src: &mut dyn FnMut(&str, &mut String),
) {
    ranges.with(|ranges| {
        ranges.extend(lints.iter().map(|x| x.data.decl_range));
        ranges.extend(passes.iter().map(|x| x.decl_sp.range));
        ranges.sort_unstable_by_key(|x| x.start);

        lints.sort_unstable_by_key(|x| x.name);
        passes.sort_by_key(|x| x.name);

        let mut ranges = ranges.iter();
        let pos = if let Some(range) = ranges.next() {
            copy_src(&src[..range.start as usize], dst);
            for lint in &*lints {
                lint.gen_mac(dst);
                dst.push_str("\n\n");
            }
            for pass in passes {
                pass.lints.sort_unstable();
                pass.gen_mac(dst);
                dst.push_str("\n\n");
            }
            range.end
        } else {
            copy_src(src, dst);
            return;
        };

        let pos = ranges.fold(pos, |start, range| {
            let s = &src[start as usize..range.start as usize];
            // Don't keep whitespace between declarations.
            if !s.trim_start().is_empty() {
                let s = if src[..pos as usize].ends_with("\n\n")
                    && let Some(s) = s.strip_prefix("\n\n")
                {
                    // Empty line before and after. Remove one of them.
                    s
                } else {
                    // Remove the line end immediately proceeding a declaration.
                    s.strip_prefix('\n').unwrap_or(s)
                };
                copy_src(s, dst);
            }
            range.end
        });

        // Since we always generate an empty line at the end, make sure to always skip it.
        let s = &src[pos as usize..];
        let s = s.strip_prefix('\n').map_or(s, |s| s.strip_prefix('\n').unwrap_or(s));
        copy_src(s, dst);
    });
}
