// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

pub static LINTS: &[&::declare_clippy_lint::LintInfo] = &[
    crate::AS_POINTER_UNDERSCORE_INFO,
    crate::AS_PTR_CAST_MUT_INFO,
    crate::AS_UNDERSCORE_INFO,
    crate::BORROW_AS_PTR_INFO,
    crate::CAST_ABS_TO_UNSIGNED_INFO,
    crate::CAST_ENUM_CONSTRUCTOR_INFO,
    crate::CAST_ENUM_TRUNCATION_INFO,
    crate::CAST_LOSSLESS_INFO,
    crate::CAST_NAN_TO_INT_INFO,
    crate::CAST_POSSIBLE_TRUNCATION_INFO,
    crate::CAST_POSSIBLE_WRAP_INFO,
    crate::CAST_PRECISION_LOSS_INFO,
    crate::CAST_PTR_ALIGNMENT_INFO,
    crate::CAST_SIGN_LOSS_INFO,
    crate::CAST_SLICE_DIFFERENT_SIZES_INFO,
    crate::CAST_SLICE_FROM_RAW_PARTS_INFO,
    crate::CHAR_LIT_AS_U8_INFO,
    crate::CONFUSING_METHOD_TO_NUMERIC_CAST_INFO,
    crate::FN_TO_NUMERIC_CAST_INFO,
    crate::FN_TO_NUMERIC_CAST_ANY_INFO,
    crate::FN_TO_NUMERIC_CAST_WITH_TRUNCATION_INFO,
    crate::MANUAL_DANGLING_PTR_INFO,
    crate::PTR_AS_PTR_INFO,
    crate::PTR_CAST_CONSTNESS_INFO,
    crate::REF_AS_PTR_INFO,
    crate::UNNECESSARY_CAST_INFO,
    crate::ZERO_PTR_INFO,
];
