// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

pub static LINTS: &[&::declare_clippy_lint::LintInfo] = &[
    crate::as_pointer_underscore::AS_POINTER_UNDERSCORE_INFO,
    crate::as_ptr_cast_mut::AS_PTR_CAST_MUT_INFO,
    crate::as_underscore::AS_UNDERSCORE_INFO,
    crate::borrow_as_ptr::BORROW_AS_PTR_INFO,
    crate::cast_abs_to_unsigned::CAST_ABS_TO_UNSIGNED_INFO,
    crate::cast_enum_constructor::CAST_ENUM_CONSTRUCTOR_INFO,
    crate::cast_lossless::CAST_LOSSLESS_INFO,
    crate::cast_nan_to_int::CAST_NAN_TO_INT_INFO,
    crate::cast_possible_truncation::CAST_ENUM_TRUNCATION_INFO,
    crate::cast_possible_truncation::CAST_POSSIBLE_TRUNCATION_INFO,
    crate::cast_possible_wrap::CAST_POSSIBLE_WRAP_INFO,
    crate::cast_precision_loss::CAST_PRECISION_LOSS_INFO,
    crate::cast_ptr_alignment::CAST_PTR_ALIGNMENT_INFO,
    crate::cast_sign_loss::CAST_SIGN_LOSS_INFO,
    crate::cast_slice_different_sizes::CAST_SLICE_DIFFERENT_SIZES_INFO,
    crate::cast_slice_from_raw_parts::CAST_SLICE_FROM_RAW_PARTS_INFO,
    crate::char_lit_as_u8::CHAR_LIT_AS_U8_INFO,
    crate::confusing_method_to_numeric_cast::CONFUSING_METHOD_TO_NUMERIC_CAST_INFO,
    crate::fn_to_numeric_cast::FN_TO_NUMERIC_CAST_INFO,
    crate::fn_to_numeric_cast_any::FN_TO_NUMERIC_CAST_ANY_INFO,
    crate::fn_to_numeric_cast_with_truncation::FN_TO_NUMERIC_CAST_WITH_TRUNCATION_INFO,
    crate::manual_dangling_ptr::MANUAL_DANGLING_PTR_INFO,
    crate::ptr_as_ptr::PTR_AS_PTR_INFO,
    crate::ptr_cast_constness::PTR_CAST_CONSTNESS_INFO,
    crate::ref_as_ptr::REF_AS_PTR_INFO,
    crate::unnecessary_cast::UNNECESSARY_CAST_INFO,
    crate::zero_ptr::ZERO_PTR_INFO,
];
