[package]
name = "lintcheck"
version = "0.0.1"
description = "tool to monitor impact of changes in Clippys lints on a part of the ecosystem"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/rust-clippy"
categories = ["development-tools"]
edition = "2021"
publish = false

[dependencies]
cargo_metadata = "0.14"
clap = "3.1"
flate2 = "1.0"
rayon = "1.5.1"
serde = { version = "1.0", features = ["derive"] }
tar = "0.4"
toml = "0.5"
ureq = "2.2"
walkdir = "2.3"

[features]
deny-warnings = []
