name: Clippy Test (bors)

on:
  push:
    branches:
      - auto
      - try

env:
  RUST_BACKTRACE: 1
  CARGO_TARGET_DIR: '${{ github.workspace }}/target'
  NO_FMT_TEST: 1
  CARGO_INCREMENTAL: 0
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

defaults:
  run:
    shell: bash

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
      with:
        github_token: "${{ secrets.github_token }}"

    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        ref: ${{ github.ref }}

    # Run
    - name: Check Changelog
      run: |
        MESSAGE=$(git log --format=%B -n 1)
        PR=$(echo "$MESSAGE" | grep -o "#[0-9]*" | head -1 | sed -e 's/^#//')
        body=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s "https://api.github.com/repos/rust-lang/rust-clippy/pulls/$PR" | \
          python -c "import sys, json; print(json.load(sys.stdin)['body'])")
        output=$(grep "^changelog:\s*\S" <<< "$body" | sed "s/changelog:\s*//g") || {
          echo "ERROR: PR body must contain 'changelog: ...'"
          exit 1
        }
        if [[ "$output" = "none" ]]; then
          echo "WARNING: changelog is 'none'"
        else
          echo "changelog: $output"
        fi
      env:
        PYTHONIOENCODING: 'utf-8'
  base:
    needs: changelog
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        host: [x86_64-unknown-linux-gnu, i686-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-msvc]
        exclude:
        - os: ubuntu-latest
          host: x86_64-apple-darwin
        - os: ubuntu-latest
          host: x86_64-pc-windows-msvc
        - os: macos-latest
          host: x86_64-unknown-linux-gnu
        - os: macos-latest
          host: i686-unknown-linux-gnu
        - os: macos-latest
          host: x86_64-pc-windows-msvc
        - os: windows-latest
          host: x86_64-unknown-linux-gnu
        - os: windows-latest
          host: i686-unknown-linux-gnu
        - os: windows-latest
          host: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    # NOTE: If you modify this job, make sure you copy the changes to clippy.yml
    steps:
    # Setup
    - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
      with:
        github_token: "${{ secrets.github_token }}"

    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Install toolchain
      run: rustup show active-toolchain

    # Run
    - name: Set LD_LIBRARY_PATH (Linux)
      if: runner.os == 'Linux'
      run: |
        SYSROOT=$(rustc --print sysroot)
        echo "LD_LIBRARY_PATH=${SYSROOT}/lib${LD_LIBRARY_PATH+:${LD_LIBRARY_PATH}}" >> $GITHUB_ENV
    - name: Link rustc dylib (MacOS)
      if: runner.os == 'macOS'
      run: |
        SYSROOT=$(rustc --print sysroot)
        sudo mkdir -p /usr/local/lib
        sudo find "${SYSROOT}/lib" -maxdepth 1 -name '*dylib' -exec ln -s {} /usr/local/lib \;
    - name: Set PATH (Windows)
      if: runner.os == 'Windows'
      run: |
        SYSROOT=$(rustc --print sysroot)
        echo "$SYSROOT/bin" >> $GITHUB_PATH

    - name: Build
      run: cargo build --features deny-warnings,internal

    - name: Test
      if: runner.os == 'Linux'
      run: cargo test --features deny-warnings,internal

    - name: Test
      if: runner.os != 'Linux'
      run: cargo test --features deny-warnings,internal -- --skip dogfood

    - name: Test clippy_lints
      run: cargo test --features deny-warnings,internal
      working-directory: clippy_lints

    - name: Test clippy_utils
      run: cargo test --features deny-warnings,internal
      working-directory: clippy_utils

    - name: Test rustc_tools_util
      run: cargo test --features deny-warnings
      working-directory: rustc_tools_util

    - name: Test clippy_dev
      run: cargo test --features deny-warnings
      working-directory: clippy_dev

    - name: Test clippy-driver
      run: bash .github/driver.sh
      env:
        OS: ${{ runner.os }}

  metadata_collection:
    needs: changelog
    runs-on: ubuntu-latest

    steps:
     # Setup
    - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
      with:
        github_token: "${{ secrets.github_token }}"

    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Install toolchain
      run: rustup show active-toolchain

    - name: Test metadata collection
      run: cargo collect-metadata

    - name: Test lint_configuration.md is up-to-date
      run: |
        echo "run \`cargo collect-metadata\` if this fails"
        git update-index --refresh

  integration_build:
    needs: changelog
    runs-on: ubuntu-latest

    steps:
    # Setup
    - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
      with:
        github_token: "${{ secrets.github_token }}"

    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Install toolchain
      run: rustup show active-toolchain

    # Run
    - name: Build Integration Test
      env:
        CARGO_PROFILE_DEV_SPLIT_DEBUGINFO: off
      run: cargo test --test integration --features integration --no-run

    # Upload
    - name: Extract Binaries
      run: |
        DIR=$CARGO_TARGET_DIR/debug
        rm $DIR/deps/integration-*.d
        mv $DIR/deps/integration-* $DIR/integration
        find $DIR ! -executable -o -type d ! -path $DIR | xargs rm -rf
        rm -rf $CARGO_TARGET_DIR/release

    - name: Upload Binaries
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target

  integration:
    needs: integration_build
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        integration:
        - 'rust-lang/cargo'
        # FIXME: re-enable once fmt_macros is renamed in RLS
        # - 'rust-lang/rls'
        - 'rust-lang/chalk'
        - 'rust-lang/rustfmt'
        - 'Marwes/combine'
        - 'Geal/nom'
        - 'rust-lang/stdarch'
        - 'serde-rs/serde'
        # FIXME: chrono currently cannot be compiled with `--all-targets`
        # - 'chronotope/chrono'
        - 'hyperium/hyper'
        - 'rust-random/rand'
        - 'rust-lang/futures-rs'
        - 'rust-itertools/itertools'
        - 'rust-lang-nursery/failure'
        - 'rust-lang/log'

    runs-on: ubuntu-latest

    steps:
    # Setup
    - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
      with:
        github_token: "${{ secrets.github_token }}"

    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Install toolchain
      run: rustup show active-toolchain

    # Download
    - name: Download target dir
      uses: actions/download-artifact@v1
      with:
        name: target
        path: target

    - name: Make Binaries Executable
      run: chmod +x $CARGO_TARGET_DIR/debug/*

    # Run
    - name: Test ${{ matrix.integration }}
      run: |
        RUSTUP_TOOLCHAIN="$(rustup show active-toolchain | grep -o -E "nightly-[0-9]{4}-[0-9]{2}-[0-9]{2}")" \
          $CARGO_TARGET_DIR/debug/integration
      env:
        INTEGRATION: ${{ matrix.integration }}

  # These jobs doesn't actually test anything, but they're only used to tell
  # bors the build completed, as there is no practical way to detect when a
  # workflow is successful listening to webhooks only.
  #
  # ALL THE PREVIOUS JOBS NEED TO BE ADDED TO THE `needs` SECTION OF THIS JOB!

  end-success:
    name: bors test finished
    if: github.event.pusher.name == 'bors' && success()
    runs-on: ubuntu-latest
    needs: [changelog, base, metadata_collection, integration_build, integration]

    steps:
      - name: Mark the job as successful
        run: exit 0

  end-failure:
    name: bors test finished
    if: github.event.pusher.name == 'bors' && (failure() || cancelled())
    runs-on: ubuntu-latest
    needs: [changelog, base, metadata_collection, integration_build, integration]

    steps:
      - name: Mark the job as a failure
        run: exit 1
